# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Contract Test

on:
  push:
    branches: [master, prod]
  pull_request:
    branches: [master, prod]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Backend
        uses: actions/setup-node@v2
        with:
          node-version: '16.17.1'
          cache: 'yarn'
      - run: cd evm_contracts && yarn install
      - run: cd evm_contracts && yarn run test
